### ISSUE TITLE
(again) stuff not appearing in Activities...

### ISSUE THREAD

**Issue by damianodamiani** [readchina/readchina.github.io#290]
Hi, so the last two posts are again missing, one for 10 June and one for 20 June (today). In the local build they appear just fine, any ideas what's the issue? thanks...!

**Comment by whalekeykeeper** [comment]
The reason is that: the last build remotely was done two days ago and those two posts were regarded as future dated posts back then. If Lena later today approve and merge any of our two new PRs, this should be solved.
<img width="1040" alt="Screenshot 2023-06-21 at 09 42 15" src="https://github.com/readchina/readchina.github.io/assets/46596921/2b4700ca-5174-48ab-9210-6a1fc64afe3a">

However, I will keep having a look at the reason why our GitHub Action is not automatically running every week (If it was. Though I am not 100% sure about it, gonna check).

**Comment by whalekeykeeper** [comment]
As expected, after new PRs were merged, the GitHub Action was triggered. Now the "future dated posts" are available.

**Comment by duncdrum** [comment]
You guys can also manually trigger a ci run on the action tab here in the browser
